name: Go

on:
  workflow_dispatch:
#  push:
#  pull_request:
    #branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.5

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push the Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
          ghcr.io/playpals-studio/gameserver-ingress-controller:latest
          ghcr.io/playpals-studio/gameserver-ingress-controller:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
